### ISSUE TITLE
About H2O Test

### ISSUE THREAD

**Issue by XIAOLIANG64** [s-shamil/HandFormer#1]
Thank you very much for your work！
I am currently facing some issues

I would like to know how to evaluate the model on the H2O dataset.

eg:For action prediction, you need to put action id number as the key and action label number as value of the json file. action_labels.json {"modality": "hand+obj", "1": 32, "2": 11, "3": 14, ... "241": 16, "242": 22 } Make answer.zip with this json file to submit your result to CodaLab.

**Comment by s-shamil** [comment]
To evaluate the H2O test set, we followed the instructions outlined on the [CodaLab competition](https://codalab.lisn.upsaclay.fr/competitions/4820#learn_the_details-submission_format) website. The JSON file will contain keys indicating the index of each test sample obtained from action_test.txt, with the corresponding values indicating the predicted action ID.
