### ISSUE TITLE
missing landmarks2D

### ISSUE THREAD

**Issue by tqosu** [s-shamil/HandFormer#4]
I found the hand pose JSONs are not complete and many files are missing. For example, 'nusar-2021_action_both_9025-c06b_9025_user_id_2021-02-18_103624'. Is there a reason for this?

**Comment by s-shamil** [comment]
That is correct. Poses are provided for 337 out of 362 sequences in the [Assembly101](https://assembly-101.github.io/) dataset. Please report the issue in the[ original repository](https://github.com/assembly-101/assembly101-download-scripts). Thank you.
